### ISSUE TITLE
Is it possible to change the display to an ILI9341 instead?

### ISSUE THREAD

**Issue by Gabriel-El-Nino** [jfm92/microByte_firmware#11]
Hi @jfm92,

I was wondering if you could give me some pointers on how to adapt the code to use a ILI9341 display instead of the ST7789 you are using. I've tried a few things but I only get a blank screen. 

Any help would be more than appreciated! When I get it working I'll share the code back :) 

Thanks!

**Comment by jfm92** [comment]
Hi @Gabriel-El-Nino ,

Well, it shouldn't be too hard to implement that specific screen, due to I remenber (barely) that commands and logic was pretty similar to the ST7789.

First I recommend you to have an idea of the software architecture, basically is like a cake so and for this specific case is like this:
- Application -> Create the image
- HAL (Hardware abstraction layer) -> Makes required images calculus
- Driver -> Send to the display

You only need to care about developing the driver and implement it on the abstraction layer. 

https://github.com/jfm92/microByte_firmware/blob/master/components/drivers/display/display_HAL/display_HAL.c#L244

The important part to have in mind is like on the previous line that I've attached.  On those functions it makes calls to the driver, so you need to delete the driver calls, and add your ILI9341 specific functions.

A good trick is to have a look into the ST7789 driver and "recycle" the file reusing the functions, because on one hand I think that the display that you want to use, it's also and SPI display and the funcitonality it's exactly the same (send commands and data) but with different registers and data values.

For example this function most sure, it should be different, because the ILI9341 will use different registers:
https://github.com/jfm92/microByte_firmware/blob/master/components/drivers/display/ST7789/ST7789_driver.c#L236

But the rest should be more or less the same.

I'm giving a lot of information and maybe it's not very clear xD 
Summarizing, I recommend you first to make it work the display by separate with and Arduino example or somenthing simple, study the driver and try to adapt to the already existing driver. 
And a final thing, change the configuration (specially the resolution) here:

https://github.com/jfm92/microByte_firmware/blob/master/components/drivers/system_configuration/system_configuration.h#L5

I hope this helps :)

**Comment by Gabriel-El-Nino** [comment]
Hello @jfm92!! 

Thank you so much for getting back to me! 

I've been hard at work already trying to get the ILI9341 display to work with your base code. It is progressing but I am still struggling. I managed to get the displays working using arduino IDE setup without sweat. But now adapting to your base code its a little different. I am recycling your code and functions, which is easy since the ILI9341 also uses SPI communication. But my challenge is in the driver because the registers are different. And since I can't exactly just copy paste a driver either, I am writing my own. I am not experience in writing drivers but learning as I go! Here's my current progress:

https://user-images.githubusercontent.com/112965047/190591183-cd398cc9-c1db-4764-9a04-d41c81b12f66.mp4

It's not terrible but I've been over a week on a white display so it's progress! I found out CS pin is needed in most drivers, so I modified the code so I could control CS on pin 15 (and changed the backlight to another pin). 

But now, I am having a hard time writing the configuration to the display. I'm adapting some drivers from Adafruit for this display but it's not that simple. Ilitek, the company manufacturing the displays, have documentation on the display and the registers [Link here](https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf), but they SPECIFICALLY don't want to explain all the commands because - that's what they do. So for example, in the first bit of command, the command  0xEF (which I named ILI9341_START) is not explained in the documentation, but is a must for the display to work. Now I'm struggling with the ILI9341_MADCTL, or 0x36, to get the order of the display right. I also think I might have an issue with the frame rate. 

`static void ILI9341_config(ILI9341_driver_t *driver){

    const uint8_t caset[4] = {
		0x00,
		0x00,
		(driver->display_width - 1) >> 8,
		(driver->display_width - 1) & 0xff
	};
	const uint8_t raset[4] = {
		0x00,
		0x00,
		(driver->display_height - 1) >> 8,
		(driver->display_height - 1) & 0xff
	};
    
	const ILI9341_command_t init_sequence[] = {

        {ILI9341_SLPIN, 10, 0, NULL},                    // Sleep
		{ILI9341_SWRESET, 200, 0, NULL},                 // Reset
		{ILI9341_SLPOUT, 120, 0, NULL},                  // Sleep out

		{ILI9341_MADCTL, 0, 1, (const uint8_t *)"\x00"}, // Page / column address order
		{ILI9341_PIXFMT, 0, 1, (const uint8_t *)"\x55"}, // 16 bit RGB
		{ILI9341_DINVON, 0, 0, NULL},                     // Inversion on
		{ILI9341_CASET, 0, 4, (const uint8_t *)&caset},  // Set width
		{ILI9341_RASET, 0, 4, (const uint8_t *)&raset},  // Set height
		
        	{ILI9341_START,         0, 3,  (const uint8_t *)"\x03\x80\x02"},
        	{ILI9341_LCD_POWERB,    0, 3,  (const uint8_t *)"\x00\xC1\x30"},
      		{ILI9341_LCD_POWER_SEQ, 0, 4,  (const uint8_t *)"\x64\x03\x12\x81"},
        	{ILI9341_LCD_DTCA,      0, 3,  (const uint8_t *)"\x85\x00\x78"},
        	{ILI9341_LCD_POWERA,    0, 5,  (const uint8_t *)"\x39\x2C\x00\x34\x02"},
        	{ILI9341_LCD_PRC,       0, 1,  (const uint8_t *)"\x20"},
        	{ILI9341_LCD_DTCB,      0, 2,  (const uint8_t *)"\x00\x00"},
        	{ILI9341_PWCTRL1,       0, 1,  (const uint8_t *)"\x23"},          //VRH[5:0]
        	{ILI9341_PWCTRL2,       0, 1,  (const uint8_t *)"\x10"},          //SAP[2:0];BT[3:0]
        	{ILI9341_VCCR1,         0, 2,  (const uint8_t *)"\x3e\x28"},
        	{ILI9341_VCCR2,         0, 1,  (const uint8_t *)"\x86"},
        	{ILI9341_MADCTL,        0, 1,  (const uint8_t *)"\x48"},          // MX and BGR
        	{ILI9341_PIXFMT,        0, 1,  (const uint8_t *)"\x55"},
        	{ILI9341_FRMCRN1,       0, 2,  (const uint8_t *)"\x00\x1B"},      // 0x18 79Hz, 0x1B default 70Hz, 0x13 100Hz
        	{ILI9341_DISCTRL,       0, 3,  (const uint8_t *)"\x08\x82\x27"},
        	{ILI9341_LCD_3GAMMA_EN, 0, 1,  (const uint8_t *)"\x00"},
        	{ILI9341_GAMSET,        0, 1,  (const uint8_t *)"\x01"},
        	{ILI9341_GMCTRP1,      0, 15, (const uint8_t *)"\x0F\x31\x2B\x0C\x0E\x08\x4E\xF1\x37\x07\x10\x03\x0E\x09\x00"},
        	{ILI9341_GMCTRN1,      0, 15, (const uint8_t *)"\x00\x0E\x14\x03\x11\x07\x31\xC1\x48\x08\x0F\x0C\x31\x36\x0F"},
        	{ILI9341_SLPOUT,      120,  0,  NULL},           // Sleep out
		{ILI9341_DISPON,      120,  0,  NULL},           //Display on
		{ILI9341_NOP, 0, 0, NULL},                      // End of commands
	};

	ILI9341_multi_cmd(driver, init_sequence);
	ILI9341_fill_area(driver, 0x0000, 0, 0, driver->display_width, driver->display_height);
	const ILI9341_command_t init_sequence2[] = {
		{ILI9341_DISPON, 100, 0, NULL},                  // Display on
		{ILI9341_SLPOUT, 100, 0, NULL},                  // Sleep out
		{ILI9341_CASET, 0, 4, caset},
		{ILI9341_RASET, 0, 4, raset},
		{ILI9341_RAMWR, 0, 0, NULL},
		{ILI9341_NOP, 0, 0, NULL},                   // End of commands
	};
	ILI9341_multi_cmd(driver, init_sequence2);
}`

In the video you can also see that the display freezes, crashes and then reboot. Took me a while to figure it out but I discovered that its the ILI9341_set_endian (or S7789_set_endian) which is causing the crash. I modified the register command so it works out, but that was not the problem. In this set_endian function, I tried to see which _send_cmd is causing the crash but I cannot figure it out. When I have 1 commands in the init_sequence_endian, the _send_cmd function is looped twice, and when there are 2 or + commands it loops 2 or + times. So somehow, when setting the endian, the _send_cmd loops 1 more times than it should, and this seems to cause the crash.

`void ILI9341_set_endian(ILI9341_driver_t *driver){
    ESP_LOGI(TAG, "ILI9341_set_endian func start");
	const ILI9341_command_t init_sequence_endian[] = {
		//{ILI9341_INTFCTRL, 0, 3, (const uint8_t *)"\x00\x00\x20"},
		{ILI9341_NORON, 0, 0, NULL}, 
	};
    ESP_LOGI(TAG,"Start of multi_cmd");
	ILI9341_multi_cmd(driver, init_sequence_endian);
    ESP_LOGI(TAG, "ILI9341_set_endian func end");
}`

and the _send_cmd function where I added the ESP_LOGI line. I didn't modify the multi_command. 

`static void ILI9341_send_cmd(ILI9341_driver_t *driver, const ILI9341_command_t *command){
    spi_transaction_t *return_trans;
	spi_transaction_t data_trans;
    
    // Check if the SPI queue is empty
    ILI9341_queue_empty(driver);

    // Send the command
	memset(&data_trans, 0, sizeof(data_trans));
	data_trans.length = 8; // 8 bits
	data_trans.tx_buffer = &command->command;
	data_trans.user = &driver->command;

	spi_device_queue_trans(driver->spi, &data_trans, portMAX_DELAY);
	spi_device_get_trans_result(driver->spi, &return_trans, portMAX_DELAY);

    // Send the data if the command has.
	if (command->data_size > 0) {
		memset(&data_trans, 0, sizeof(data_trans));
		data_trans.length = command->data_size * 8;
		data_trans.tx_buffer = command->data;
		data_trans.user = &driver->data;

		spi_device_queue_trans(driver->spi, &data_trans, portMAX_DELAY);
		spi_device_get_trans_result(driver->spi, &return_trans, portMAX_DELAY);
	}

    // Wait the required time
	if (command->wait_ms > 0) {
		vTaskDelay(command->wait_ms / portTICK_PERIOD_MS);
	}
    ESP_LOGI(TAG, "ILI9341_send_cmd done");
}`

And this is the crash message I get from the debug: 

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/112965047/190597262-c5a143e7-6bd7-4b34-82f5-bfa661595c22.png">

I am lost, I am not sure why the code crashes in this specific set_endian function. Would you have an idea? I am really determinate to get this working, so will work on it till I get it done. But any help is much much appreciated.

Once I get it working I will put the code up :)

Thanks a lot for everything!

**Comment by Gabriel-El-Nino** [comment]
Update on progress: 

Im slowly getting there, I finally (more or less) got the right config for the screen and managed to play some games. However, I am still having issue with the sizing of the display.

I changed these three instances of the screen width to match 320:

- https://github.com/jfm92/microByte_firmware/blob/a25c8e13c794f1392a73e279d257173ea38375e3/components/drivers/display/display_HAL/display_HAL.c#L52
- https://github.com/jfm92/microByte_firmware/blob/a25c8e13c794f1392a73e279d257173ea38375e3/components/drivers/system_configuration/system_configuration.h#L6
- https://github.com/jfm92/microByte_firmware/blob/a25c8e13c794f1392a73e279d257173ea38375e3/components/boot_screen/boot_screen.c#L27

But it's not working. I'm getting some funky results... However, I think I know the line which is causing me trouble. 

https://github.com/jfm92/microByte_firmware/blob/a25c8e13c794f1392a73e279d257173ea38375e3/components/drivers/display/display_HAL/display_HAL.c#L54

In this line you specify the buffer size of the screen to be 20 * 240. Could you maybe explain why or how did you come to 20 * 240? In the other instance of the screen buffer, the value is 20. 

If you can explain me this line it would help me greatly. Thank you!

**Comment by Gabriel-El-Nino** [comment]
Okay this took a while, but I finally figured out (almost everything). There are still some bugs and issues with the set_window, but the screen is working as intended! 

Here's all my code if anyone wants to try a bigger screen. If anyone has any questions they can always ask, I'm happy to help!

https://github.com/Gabriel-El-Nino/microByte_firmware_El_Nino_Flavor
